### ISSUE TITLE
XModule distribution not found

### ISSUE THREAD

**Issue by chemseddineZ** [openedx-unsupported/devstack#130]
I'm not able to run edX studio with `paver devstack studio` as I 'm having an XModule distribution error 

```
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/bin/xmodule_assets", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'XModule==0.1.1' distribution was not found and is required by the application


Captured Task Output:
---------------------

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
python manage.py cms --settings=devstack reindex_course --setup
---> pavelib.assets.update_assets
python manage.py lms --settings=devstack preprocess_assets lms/static/sass/*.scss lms/static/themed_sass
xmodule_assets common/static/xmodule

Build failed running pavelib.servers.devstack: Subprocess return code: 1
```
How can I solve this issue without having to reinstall devstack as I don't want to lose all the work I've done

**Comment by clintonb** [comment]
Why are you running `paver devstack studio`? The services are already run when you run either `make dev.up` or `make dev.sync.up`.

**Comment by chemseddineZ** [comment]
I've been using this command since the begining, I'm just following the documentation

**Comment by clintonb** [comment]
Note that this is the *Docker-based* devstack which is still in the alpha phase. See the README for a link to Vagrant devstack, or to learn how to use Docker Devstack.
