### ISSUE TITLE
Issue during provisioning

### ISSUE THREAD

**Issue by marjev** [openedx-unsupported/devstack#166]
```
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform && NO_PREREQ_INSTALL=1 paver update_db --settings devstack_docker'
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/bin/paver", line 11, in <module>
    sys.exit(main())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 846, in _launch_pavement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
  File "pavement.py", line 14, in <module>
    from pavelib import *
  File "pavelib/__init__.py", line 4, in <module>
    from . import assets, servers, docs, prereqs, quality, tests, js_test, i18n, bok_choy, acceptance_test
  File "pavelib/assets.py", line 23, in <module>
    from .utils.envs import Env
  File "pavelib/utils/envs.py", line 18, in <module>
    class Env(object):
  File "pavelib/utils/envs.py", line 24, in Env
    REPO_ROOT = path(__file__).abspath().parent.parent.parent
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/path.py", line 293, in abspath
    return self._next_class(self.module.abspath(self))
  File "/edx/app/edxapp/venvs/edxapp/lib/python2.7/posixpath.py", line 362, in abspath
    cwd = os.getcwdu()
OSError: [Errno 2] No such file or directory
make: *** [dev.provision.run] Error 1
```

**Comment by gsong** [comment]
There was an attempt to resolve this with edx/edx-platform#15531. However, I'm still experiencing a problem.

Environment:

* macOS 10.12.5
* Docker CE 17.06.0-ce-mac19 (18663)

Here's what I did:
1. Removed all data using the Docker preferences reset feature.
2. Made sure all repos are up to date on `master`
3. Run `make dev.provision`

<details>
<summary>Error log</summary>
<pre>
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/ed$
-platform && NO_PREREQ_INSTALL=1 paver update_db --settings devstack_docker'
Attempt 1/60 to get an absolute path failed
…
Attempt 61/60 to get an absolute path failed
Unable to determine the absolute path of the edx-platform repo, aborting
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/bin/paver", line 11, in <module>
    sys.exit(main())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 846, in _launch_pavement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
  File "pavement.py", line 14, in <module>
    from pavelib import *
  File "pavelib/__init__.py", line 4, in <module>
    from . import assets, servers, docs, prereqs, quality, tests, js_test, i18n, bok_choy, acceptance_test
  File "pavelib/assets.py", line 23, in <module>
    from .utils.envs import Env
  File "pavelib/utils/envs.py", line 46, in <module>
    class Env(object):
  File "pavelib/utils/envs.py", line 52, in Env
    REPO_ROOT = repo_root()
  File "pavelib/utils/envs.py", line 33, in repo_root
    absolute_path = file_path.abspath()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/path.py", line 293, in abspath
    return self._next_class(self.module.abspath(self))
  File "/edx/app/edxapp/venvs/edxapp/lib/python2.7/posixpath.py", line 362, in abspath
    cwd = os.getcwdu()
OSError: [Errno 2] No such file or directory
make: *** [dev.provision.run] Error 1
</pre>
</details>

**Comment by gsong** [comment]
This has been resolved.

**Comment by marjev** [comment]
Awesome, thanks for letting me know!
