### ISSUE TITLE
`make dev.provision` fails due to invalid requirements

### ISSUE THREAD

**Issue by gsong** [openedx-unsupported/devstack#185]
During provisioning, we run into the following issue:

<details>
<summary>Provision Error Log</summary>
<pre>
Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 52, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", lin
e 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py"
, line 115, in populate
    app_config.ready()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/admin/app
s.py", line 22, in ready
    self.module.autodiscover()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/admin/__i
nit__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/module_load
ing.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/admin/__init_
_.py", line 14, in <module>
    from django_object_actions import DjangoObjectActions
ImportError: No module named django_object_actions
</pre>
</details>

There is a PR in progress to fix this issue: edx/edx-platform#15582.

**Comment by gsong** [comment]
I've confirmed that edx/edx-platform#15582 fixes this issue. We should close this once that PR is merged.

**Comment by clintonb** [comment]
edx/edx-platform#15582 has been merged.
