### ISSUE TITLE
'XModule' distribution was not found

### ISSUE THREAD

**Issue by jmatsushita** [openedx-unsupported/devstack#79]
Not sure if it's connected to #78 but I also get a Studio install without asset compiled which seem to have been experienced by others and [reported in slack](https://openedx.slack.com/archives/C0EFVC6RK/p1490295574863073).

```
# paver update_assets --settings devstack_docker
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/bin/xmodule_assets", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'XModule' distribution was not found and is required by the application


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
xmodule_assets common/static/xmodule

Build failed running pavelib.assets.update_assets: Subprocess return code: 1
```

**Comment by jmatsushita** [comment]
Running `pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/local.txt` from `/edx/app/edxapp/edx-platform` and then `paver update_assets --settings devstack_docker` seems to work and make studio's theme load correctly!

Unfortunaltely it doesn't have an effect on #78. Leaving this open as it might be related to [this comment on the slack devstack channel](https://openedx.slack.com/archives/C0EFVC6RK/p1490200964849988):
>  Clinton Blackburn
> I've seen issues with this recently. When we attempt to build assets, we first install dependencies. > This installation fails, and I haven't had time to determine why.
> Posted in #docker March 22nd at 5:42 PM

**Comment by vkaracic** [comment]
I used to have this issue, but after reinstalling the devstack the assets seem to all be compiled.

**Comment by macdiesel** [comment]
I believe this issue has been resolved.
