### ISSUE TITLE
Error while running make dev.provision command

### ISSUE THREAD

**Issue by cheku-bhutan** [openedx-unsupported/devstack#921]
I am stuck with the issue below while running make dev.provision command:

pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt
ERROR: Exception:
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 367, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 188, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 313, in __init__
    super().__init__(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 323, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 607, in prepare_editable_requirement
    req.update_editable()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 612, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url, verbosity=0)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 526, in obtain
    existing_url = self.get_remote_url(dest)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 369, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

Captured Task Output:
---------------------

---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt

Build failed running pavelib.prereqs.install_prereqs: Subprocess return code: 2
make[1]: *** [impl-dev.provision] Error 1
Would you like to assist devstack development by sending anonymous usage metrics to edX? Run `make metrics-opt-in` to learn more!
make: *** [dev.provision] Error 2

**Comment by john40fy** [comment]
@cheku-bhutan I had the same issue, and wonder how you solved it.

**Comment by rqasim420-69** [comment]
@cheku-bhutan I also have the same issue. Can you please upload the solution?

**Comment by cheku-bhutan** [comment]
In my case it was the issue of python version. While creating python environment you have to use python3.

`python3 -m venv env`

**Comment by rqasim420-69** [comment]
@john40fy this issue was on the edx team's end, it is resolved now. You can check the thread here: https://app.slack.com/client/T02SNA1T6/threads/thread/CDAG4KN2C-1650604976.967079

**Comment by john40fy** [comment]
@rqasim420-69 Thank you for the info. I just pulled the latest version and it worked ok!

**Comment by rqasim420-69** [comment]
@john40fy welcome. :)
